proyecto/Areas/Bcri/Controllers/PivotTableController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Bcri.Core.Bussines;
using proyecto.Areas.Bcri.Models;
using DNF.Security.Bussines;
using DNF.Structure.Bussines;
using Newtonsoft.Json;

namespace proyecto.Areas.Bcri.Controllers
{
    [Authenticated]
    public class PivotTableController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.tmpDataSource = GetPermissionsPivotCube();
            ViewBag.Title = "Pivot Table";

            return View();
        }

        public JsonResult FilterInfo(string dataSource, string dateRange, string dateStart, string dateEnd)
        {
            return Json(GetData(dataSource, dateRange, dateStart, dateEnd), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult LoadQueryInfo(int idDataSource)
        {
            var query = GetSavedQueries(idDataSource);
            return Json(query, JsonRequestBehavior.AllowGet);
        }
        public JsonResult CheckQuery(string nameQuery)
        {
            string menssageError;

            try
            {
                if (string.IsNullOrEmpty(nameQuery))
                    return Json(true, JsonRequestBehavior.AllowGet);

                var s = PivotQuery.Dao.GetAll()
                    .Where(z => string.Equals(z.Name.Trim(), nameQuery, StringComparison.CurrentCultureIgnoreCase));
                if (!s.Any())
                    return Json(true, JsonRequestBehavior.AllowGet);

                menssageError = string.Format(CultureInfo.InvariantCulture,
                    "The report {0} already exists in the database.", nameQuery);
            }
            catch (Exception ex)
            {

                throw;
            }

            return Json(menssageError, JsonRequestBehavior.AllowGet);
        }
        public JsonResult LoadQuery(int idSelectedQuery)
        {
            object result = null;

            try
            {
                if (idSelectedQuery <= 0) return Json(null, JsonRequestBehavior.AllowGet);

                var query = PivotQuery.Dao.Get(idSelectedQuery);
                if (query != null)
                {
                    result = query.PivotQueryStructs.Select(s => new
                    {
                        hiddenAttributes = string.IsNullOrEmpty(s.HiddenAttributes) ? new string[] { } : s.HiddenAttributes.Trim().Replace(" ", "").Split(','),
                        menuLimit = Convert.ToInt32(s.MenuLimit),
                        cols = string.IsNullOrEmpty(s.Cols) ? new string[] { } : s.Cols.Trim().Replace(" ", "").Split(','),
                        rows = string.IsNullOrEmpty(s.Rows) ? new string[] { } : s.Rows.Trim().Replace(" ", "").Split(','),
                        vals = string.IsNullOrEmpty(s.Vals) ? new string[] { } : s.Vals.Trim().Replace(" ", "").Split(','),
                        exclusions = s.Exclusions,
                        inclusions = s.Inclusions,
                        unusedAttrsVertical = Convert.ToInt32(s.UnusedAttrsVertical),
                        autoSortUnusedAttrs = Convert.ToBoolean(s.AutoSortUnusedAttrs),
                        inclusionsInfo = s.InclusionsInfo,
                        aggregatorName = s.AggregatorName,
                        rendererName = s.RendererName
                    });
                }
            }
            catch (Exception)
            {

                throw;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult SaveQuery(string dataJson)
        {
            object result = null;

            try
            {
                var obj = JsonConvert.DeserializeObject<Dictionary<string, string>>(dataJson);
                if (obj != null)
                {
                    var objData = JsonConvert.DeserializeObject<JsonQueryPivot>(obj["dataNewQuery"]);
                    if (objData != null)
                    {
                        var query = Convert.ToInt32(obj["idSelectedQuery"]) == 0
                            ? new PivotQuery()
                            : PivotQuery.Dao.Get(Convert.ToInt32(obj["idSelectedQuery"]));

                        var isNew = query.IsNew();
                        if (isNew)
                        {
                            query.Name = obj["nameNewQuery"];
                            query.Code = obj["nameNewQuery"];
                            query.User = Current.User;
                            query.RepositoryConfig = new RepositoryConfig { Id = Convert.ToInt32(obj["idDataSource"]) };
                            query.Save();
                        }

                        var structQuery = isNew
                            ? new PivotQueryStruct()
                            : query.PivotQueryStructs?.FirstOrDefault();

                        structQuery.HiddenAttributes = objData.HiddenAttributes.Count == 0 ? string.Empty : string.Join(", ", objData.HiddenAttributes);
                        structQuery.MenuLimit = objData.MenuLimit.ToString();
                        structQuery.Cols = objData.Cols.Count == 0 ? string.Empty : string.Join(", ", objData.Cols);
                        structQuery.Rows = objData.Rows.Count == 0 ? string.Empty : string.Join(", ", objData.Rows);
                        structQuery.Vals = objData.Vals.Count == 0 ? string.Empty : string.Join(", ", objData.Vals);
                        structQuery.Exclusions = objData.Exclusions.Count == 0 ? string.Empty : FromDictionaryToJson(objData.Exclusions);
                        structQuery.Inclusions = objData.Inclusions.Count == 0 ? string.Empty : FromDictionaryToJson(objData.Inclusions);
                        structQuery.UnusedAttrsVertical = objData.UnusedAttrsVertical.ToString();
                        structQuery.AutoSortUnusedAttrs = objData.AutoSortUnusedAttrs.ToString();
                        structQuery.InclusionsInfo = objData.InclusionsInfo.Count == 0 ? string.Empty : FromDictionaryToJson(objData.InclusionsInfo);
                        structQuery.AggregatorName = objData.AggregatorName;
                        structQuery.RendererName = objData.RendererName;
                        structQuery.PivotQuery = query;
                        structQuery.Save();

                        result = query.Id;
                    }
                }
            }
            catch (Exception ex)
            {

                throw;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult DeleteQuery(int idSelectedQuery)
        {
            try
            {
                if (idSelectedQuery <= 0) return Json(null, JsonRequestBehavior.AllowGet);

                var query = PivotQuery.Dao.Get(idSelectedQuery);
                PivotQueryStruct.Dao.Delete(query.PivotQueryStructs);
                query.Delete();
            }
            catch (Exception)
            {

                throw;
            }

            return Json("Ok", JsonRequestBehavior.AllowGet);
        }

        #region private -> methods
        private static List<SelectListItem> GetPermissionsPivotCube()
        {
            var cubos = RepositoryConfig.Dao.GetAll()
                .Where(x => Current.User.HasAccess("CUBE_PIVOT_" + x.Code.Trim()));

            return cubos.ToListItem();
        }
        private static List<dynamic> GetData(string repositoryId, string dateRange, string dateStart, string dateEnd)
        {
            var data = new List<dynamic>();

            try
            {
                if (!string.IsNullOrEmpty(repositoryId))
                {
                    var parameters = GetParametersArray(dateRange, dateStart, dateEnd);
                    

                    var repositoryConfig = RepositoryConfig.Dao.Get(repositoryId); ;

                    if (repositoryConfig == null) return null;

                    var repositories = Repository.Dao.GetByPeriod(repositoryConfig, parameters[0], parameters[1]);
                    if (repositories == null) return null;

                    //repositoryConfig.Entity = Entity.Dao.Get(repositoryConfig.Entity.Id);
                    //var type = Type.GetType(repositoryConfig.Entity.Class + "," + repositoryConfig.Entity.Assembly);

                    var entity = Entity.Dao.Get(repositoryConfig.Entity.Id);
                    var type = Type.GetType(entity.Class + "," + entity.Assembly);

                    var dao = type?.GetProperty("Dao").GetValue(null, null);

                    var methodInfo = dao?.GetType().GetMethod("GetBy", new[] { typeof(string), typeof(IEnumerable<long>) });
                    if (methodInfo == null) return null;

                    var parametersInfo = methodInfo.GetParameters();
                    var result = (methodInfo.Invoke(dao, parametersInfo.Length == 0 ? null : new object[] { "Repository", repositories.Select(x => x.Id) }) as IEnumerable<IToPivot>);
                    if (result != null)
                        data = result.Select(x => x.ToPivot()).ToList();
                }
            }
            catch (Exception ex)
            {
                throw;
            }

            return data;
        }
        private static List<SelectListItem> GetSavedQueries(int idDataSource)
        {
            var queriesByPivotCube = PivotQuery.Dao.GetByFilter(new { RepositoryConfig_Id = idDataSource })
                .OrderBy(o => o.Name);

            return queriesByPivotCube.ToListItem(" ");
        }
        private static string FromDictionaryToJson(Dictionary<string, List<object>> dictionary)
        {
            var dictmp = new Dictionary<string, List<string>>();
            foreach (var keyDic in dictionary)
            {
                var list = keyDic.Value.Select(valueDic => $"\"{valueDic}\"").ToList();
                dictmp.Add(keyDic.Key, list);
            }

proyecto/Areas/Bcri/Views/PivotTable/Index.cshtml
@{var Res = proyecto.Res.res;}
<div class="container-fluid">
    <div class="row">
        <h1 class="page-header">Pivot Table</h1>
    </div>
    <div class="row">
        <div id="filterDiv">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button id="btnToggleFilters" type="button" class="btn btn-primary" data-toggle="collapse" data-target="#panelBodyFilter">
                        @Res.data<span class="fa fa-unsorted" aria-hidden="true"></span>
                    </button>
                </div>
                <div class="panel-body collapse" id="panelBodyFilter">
                    <div class="row" style="padding-bottom: 10px; display: inherit">
                        <div class="col-md-3">
                            <label for="selectDataSourceFilters" class="small alignText">@Res.dataSource</label>
                        </div>
                        <div class="col-md-3">
                            @Html.DropDownList("selectDataSourceFilters",
                                (List<SelectListItem>)ViewBag.tmpDataSource,
                                new { @class = "form-control input-sm", placeholder =  Res.selectDataSource })
                        </div>
                        <div class="col-md-3"></div>
                        <div class="col-md-3"></div>
                    </div>
                    <div class="row" style="padding-bottom: 2px;">
                        <div class="col-md-3">
                            <div class="" style="">
                                <label for="selectDateRangeFilters" class="small alignText">
                                    <input type="radio" name="radioFilter" id="radioFilterPeriod" value="optPeriod" checked> @Res.filterByTimeRange
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <select id="selectDateRangeFilters" class="form-control input-sm">
                                <option value="todayDate">@Res.today</option>
                                <option value="lastWeek">@Res.lastWeek</option>
                                <option value="lastMonth">@Res.lastMonth</option>
                                <option value="lastSixMonths">@Res.lastSixMonth</option>
                                <option value="lastYear">@Res.lastYear</option>
                            </select>
                        </div>
                        <div class="col-md-3"></div>
                        <div class="col-md-3">
                            <button type="button" class="btn btn-outline btn-primary" id="btnFilter">
                                <span class="fa fa-search" aria-hidden="true"></span> @Res.filter
                            </button>
                        </div>
                    </div>
                    <div class="row" style="padding-bottom: 2px;">
                        <div class="col-md-3">
                            <div>
                                <label for="selectDateRangeFilters" class="small alignText">
                                    <input type="radio" name="radioFilter" id="radioFilterDate" value="optDate">@Res.filterByDateRange
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <input type="text" class="form-control input-sm" id="filterDateFromFilters"
                                   name="filterDateFromFilters" placeholder=@Res.from>
                        </div>
                        <div class="col-md-3">
                            <input type="text" class="form-control input-sm" id="filterDateToFilters"
                                   name="filterDateToFilters" placeholder=@Res.to>
                        </div>
                        <div class="col-md-3">
                            <button type="button" class="btn btn-outline btn-primary" id="btnClearFilter">
                                <span class="fa fa-repeat" aria-hidden="true"></span> @Res.cleanFilters
                            </button>
                        </div>
                    </div>
                </div>
                @*<div class="panel-footer"></div>*@
            </div>

        </div>
    </div>
    <div class="row">
        <div id="progressBar" class="progress displayDiv">
            <div class="progress-bar progress-bar-striped active" role="progressbar"
                 aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                <span id="progressBarLabel" class="show">@Res.loading</span>
            </div>
        </div>
        <div id="dashBoard" class="dashBoard displayDiv alert-info">
            <div id="queryDiv" style="margin-bottom: -20px; padding-top: 10px; padding-right: 10px; padding-left: 10px;">
                <div class="navbar navbar-default viewHeading">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <form class="form-inline" role="form" id="valid-form-queryDiv">
                                <span class="navbar-brand">@Res.reports </span>
                                <div id="divLoadModeQuery" class="form-group" style="padding-top: 10px;">
                                    <select id="selectSavedQueries" class="form-control"></select>
                                    <button type="button" class="btn btn-outline btn-primary" id="btnAddQuery"
                                            data-toggle="tooltip" data-placement="top" title= @Res.saveNewReport>
                                        <span class="fa fa-plus" aria-hidden="true"></span>
                                    </button>
                                    <div id="divBtnSaveDeleteQuery" style="display: inline;">
                                        <button type="button" class="btn btn-outline btn-primary" id="btnSaveCurrentQuery"
                                                data-toggle="tooltip" data-placement="top" title=@Res.saveCurrentReport>
                                            <span class="fa fa-save" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" class="btn btn-outline btn-primary" id="btnDeleteQuery"
                                                data-toggle="tooltip" data-placement="top" title=@Res.deleteSelectedReport>
                                            <span class="fa fa-trash-o" aria-hidden="true"></span>
                                        </button>
                                    </div>
                                </div>
                                <div id="divEditModeQuery" class="form-group" style="padding-top: 10px; padding-bottom: 10px">
                                    <input type="text" class="form-control input-sm" id="inputNameNewQuery"
                                           name="inputNameNewQuery" placeholder=@Res.name>
                                    <button type="button" class="btn btn-outline btn-primary" id="btnSaveQuery"
                                            data-toggle="tooltip" data-placement="top" title=@Res.save>
                                        <span class="fa fa-check-circle-o" aria-hidden="true"></span> @Res.save
                                    </button>
                                    <button type="button" class="btn btn-outline btn-primary" id="btnCancelSaveQuery"
                                            data-toggle="tooltip" data-placement="top" title=@Res.cancel>
                                        <span class="fa fa-ban" aria-hidden="true"></span> @Res.cancel
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <textarea id="configPivotTable" class="displayDiv" readonly></textarea>
            <div id="outputPivotTable" style="padding: 10px;"></div>
        </div>
    </div>
</div>

@section styles {
    @Styles.Render("~/Content/cssPivot")
}

<div id="PivotTableJsData"
     data-loaddataurl="@Url.Action("FilterInfo", "PivotTable")"
     data-loadqueryinfourl="@Url.Action("LoadQueryInfo", "PivotTable")"
     data-checkqueryurl="@Url.Action("CheckQuery", "PivotTable")"
     data-loadqueryurl="@Url.Action("LoadQuery", "PivotTable")"
     data-savequeryurl="@Url.Action("SaveQuery", "PivotTable")"
     data-deletequeryurl="@Url.Action("DeleteQuery", "PivotTable")">
</div>

@section scripts {
    @Scripts.Render("~/bundles/pivot")
    @Scripts.Render("~/Areas/Bcri/Views/PivotTable/Index.js")
}