proyecto/Models/EstadoEmpleado.cs
using DNF.Entity;
using proyecto.Bussines;
using proyecto.Dao;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace proyecto.Bussines
{
    public partial class EstadoEmpleado : IEntityDao, IName, ICode, IOrder
    {

        public override long Id { get ; set ; }

        [Display(Name = "Nombre")]
        [Required]
        [StringLength(50, ErrorMessage = "No debe superar los 50 caracteres")]
        public string Name { get ; set; }

        //-----------RELACIONES-------------
        public int idEmpleado { get; set; }
        public List<Empleado> empleados { get; set; }
        //-----------RELACIONES-------------


        public string Code { get ; set ; }
        public int Order { get ; set; }

        public override void Delete()
        {
            Dao.Delete(this);
        }

        public override void Save()
        {
            Dao.Save(this);
        }

        private static EstadoEmpleadoDao _dao;
        public static EstadoEmpleadoDao Dao => _dao ?? (_dao = new EstadoEmpleadoDao());
    }


}

namespace proyecto.Dao
{
    public partial class EstadoEmpleadoDao : DaoDb<EstadoEmpleado>
    {

    }
}

proyecto/Controllers/EstadoEmpleadoController.cs
using proyecto.Bussines;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace proyecto.Controllers
{
    public class EstadoEmpleadoController : Controller
    {
        // GET: EstadoEmpleado
        public ActionResult Index()
        {
            List<EstadoEmpleado> lista = EstadoEmpleado.Dao.GetAll();
            return View(lista);
        }

        [HttpPost]
        public ActionResult Crear(EstadoEmpleado oEstadoEmpleado)
        {
            EstadoEmpleado estado = new EstadoEmpleado
            {
                Name = oEstadoEmpleado.Name
            };
            estado.Save();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Eliminar(int idEstado)
        {
            //hacer sp del get y delete
            var estado = EstadoEmpleado.Dao.Get(idEstado);
            EstadoEmpleado.Dao.Delete(estado);
            return RedirectToAction("Index");
        }
    }
}

proyecto/Views/EstadoEmpleado/Index.cshtml
@model IEnumerable<proyecto.Bussines.EstadoEmpleado>

@{
    ViewBag.Title = "Index";
}


<style>
    .modal-backdrop {
        backdrop-filter: blur(5px); /* Aplica desenfoque */
        background-color: rgba(0, 0, 0, 0.5) !important; /* Fondo más oscuro */
    }

    .modal-dialog {
        max-width: 80vw; /* 80% del ancho de la pantalla */
        width: 80vw;
    }

    .modal-content {
        height: auto;
        padding: 20px;
        width: 40vw;
    }

    #btnRol {
        margin-top: 20px;
        margin-bottom: 20px;
    }
</style>

<script src="~/Scripts/jquery-2.2.4.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<h2>Estados Empleado</h2>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalCrear" id="btnEstado">
    Crear Estado
</button>
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td>
                <button type="button" onclick="modalEliminar(@item.Id)" class="fa fa-trash text-danger" data-toggle="modal" data-target="#modalEliminar">
                </button>
            </td>
        </tr>
    }

</table>


@using (Html.BeginForm("Eliminar", "EstadoEmpleado", FormMethod.Post, new { @id = "frmEliminar" }))
{
    @Html.Hidden("idEstado");
}

<!-- Modal Eliminar -->
<div class="modal fade" id="modalEliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">Deseas eliminar este Estado</h4>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Eliminar()" class="btn btn-success">Aceptar</button>
            </div>
        </div>
    </div>
</div>

<!--Modal Agregar-->
<div class="modal fade" id="modalCrear" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">Crear Rol</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Crear", "EstadoEmpleado", FormMethod.Post, new { @id = "frmEstado" }))
                {
                    @Html.Label("Nombre")
                    @Html.TextBox("Name", null, new { @class = "form-control", @id = "txtNameEstado" })
                }

            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Agregar()" class="btn btn-primary">Aceptar</button>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        // Limpiar input cuando se cierra el modal
        $('#modalCrear').on('hidden.bs.modal', function () {
            $('#txtNameEstado').val('');
        });
    });

    function Agregar() {
        var frmEstado = document.getElementById("frmEstado");
        frmEstado.submit();
    }

    function modalEliminar(id) {
        document.getElementById("idEstado").value = id
    }

    function Eliminar() {
        var frmEliminar = document.getElementById("frmEliminar");
        frmEliminar.submit();
    }
</script>